(function(){
"use strict";
var KEY="lautrec_rpg_v10";
function fresh(){return{version:10,level:1,xp:0,hp:30,maxHp:30,gold:35,zone:"room",x:12,objective:"Examine le billet et retrouve la clé noire.",clues:[],inventory:[{id:"dagger",name:"Dague d'ombre",type:"Arme",power:3}],equipment:{weapon:"dagger"},quests:[{name:"Les Mémoires de l'Ombre",text:"Découvrir l'identité du quatrième Lautrec.",done:false}],journal:["Lautrec s'éveille à Veyre."],flags:{},combat:null}}
function migrate(){try{var o=JSON.parse(localStorage.getItem("lautrec_rpg_v9"))||JSON.parse(localStorage.getItem("lautrec_rpg_v3"));if(!o)return fresh();var n=fresh();n.level=o.level||1;n.xp=o.xp||0;n.hp=o.hp||30;n.maxHp=o.maxHp||30;n.gold=o.gold||35;n.zone=zones&&zones[o.zone]?o.zone:"room";n.x=typeof o.x==="number"?o.x:12;n.objective=o.objective||n.objective;n.clues=o.clues||[];n.flags=o.flags||{};n.journal=o.journal||n.journal;n.inventory=o.inventory&&o.inventory.length?o.inventory:n.inventory;return n}catch(e){return fresh()}}
function load(){try{return JSON.parse(localStorage.getItem(KEY))||migrate()}catch(e){return fresh()}}
var s=load(),held=0,target=null,near=null,running=false,last=0,raf=0;
var zones={
room:{name:"La chambre du réveil",chapter:"Chapitre I",image:"assets/story/awakening.webp",objects:[{id:"note",x:38,type:"clue",icon:"◇",name:"Billet"},{id:"key",x:70,type:"clue",icon:"⚿",name:"Clé IV"},{id:"door",x:93,type:"exit",icon:"▥",name:"Sortir",to:"street",at:6}]},
street:{name:"Les ruelles de Veyre",chapter:"Chapitre I",image:"assets/veyre-night.svg",objects:[{id:"mira",x:27,type:"npc",icon:"♟",name:"Mira"},{id:"clockmaker",x:51,type:"npc",icon:"♙",name:"Horloger"},{id:"writing",x:70,type:"clue",icon:"◇",name:"Inscription"},{id:"archives",x:83,type:"exit",icon:"▥",name:"Archives",to:"archives",at:5},{id:"sewer",x:95,type:"exit",icon:"▥",name:"Souterrains",to:"tunnels",at:6,need:"clock"}]},
archives:{name:"Les Archives royales",chapter:"Chapitre II",image:"assets/story/archives-v8.webp",objects:[{id:"sorel",x:27,type:"npc",icon:"♜",name:"Sorel"},{id:"ledger",x:57,type:"clue",icon:"◇",name:"Registre"},{id:"cabinet",x:80,type:"clue",icon:"⚿",name:"Cabinet",need:"ledger"},{id:"backA",x:3,type:"exit",icon:"‹",name:"Ruelles",to:"street",at:80}]},
tunnels:{name:"Les quatre portes",chapter:"Chapitre III",image:"assets/story/tunnels.webp",objects:[{id:"tracks",x:25,type:"clue",icon:"◇",name:"Empreintes"},{id:"masked",x:52,type:"npc",icon:"♞",name:"Gardien"},{id:"doorIV",x:90,type:"exit",icon:"Ⅳ",name:"Porte IV",to:"mirror",at:7,need:"origin"},{id:"backT",x:3,type:"exit",icon:"‹",name:"Ruelles",to:"street",at:89}]},
mirror:{name:"Le miroir impossible",chapter:"Chapitre IV",image:"assets/story/mirror.webp",objects:[{id:"reflection",x:62,type:"npc",icon:"♛",name:"Le Reflet"},{id:"bellDoor",x:93,type:"exit",icon:"▥",name:"Cloche",to:"bell",at:7,need:"truth"},{id:"backM",x:3,type:"exit",icon:"‹",name:"Souterrains",to:"tunnels",at:88}]},
bell:{name:"La Cloche noire",chapter:"Chapitre V",image:"assets/story/black-bell-v8.webp",objects:[{id:"echoes",x:48,type:"clue",icon:"◇",name:"Échos"},{id:"mechanism",x:78,type:"npc",icon:"♛",name:"Mécanisme"},{id:"backB",x:3,type:"exit",icon:"‹",name:"Miroir",to:"mirror",at:88}]}
};
var info={note:["Billet impossible","Écrit par Lautrec il y a cent ans."],key:["Clé noire IV","Elle ouvre les souvenirs."],writing:["Inscription","Lautrec ment lorsqu'il prétend avoir oublié."],clock:["Treizième heure","Une heure a été effacée."],ledger:["Quatre signatures","La même main à vingt-cinq ans d'intervalle."],decree:["Décret royal","Veyre doit oublier Lautrec."],tracks:["Empreintes identiques","Un autre Lautrec était ici."],origin:["Origine du Reflet","Le Reflet est le premier Lautrec."],truth:["Mémoire rejetée","Le Reflet porte les souvenirs refusés."],echoes:["Noms oubliés","La cloche retient les souvenirs de Veyre."]};
function $(id){return document.getElementById(id)}function zone(){return zones[s.zone]||zones.room}function has(id){return s.clues.indexOf(id)>=0}
function save(show){localStorage.setItem(KEY,JSON.stringify(s));if(show)toast("Partie sauvegardée")}
function toast(t){$("toast").textContent=t;$("toast").classList.add("on");clearTimeout(toast.t);toast.t=setTimeout(function(){$("toast").classList.remove("on")},1500)}
function xp(n){s.xp+=n;var l=1+Math.floor(s.xp/120);if(l>s.level){s.level=l;s.maxHp+=5;s.hp=s.maxHp;toast("Niveau "+l+" !")}}
function addClue(id,obj){if(has(id))return false;s.clues.push(id);xp(12);s.journal.unshift("Indice : "+info[id][0]);s.objective=obj;save();toast("Nouvel indice : "+info[id][0]);return true}
function render(){var z=zone();$("zone").textContent=z.name;$("stageName").textContent=z.name;$("chapter").textContent=z.chapter;$("objective").textContent=s.objective;$("hp").textContent=s.hp+"/"+s.maxHp;$("gold").textContent=s.gold;$("bagN").textContent=s.inventory.length;$("background").style.backgroundImage="linear-gradient(#05060a05,#05050825),url('"+z.image+"')";$("objects").innerHTML=z.objects.map(function(o){return"<button class='obj "+o.type+" "+(has(o.id)?"found":"")+"' data-id='"+o.id+"' style='left:"+o.x+"%'><i>"+o.icon+"</i><small>"+o.name+"</small><em>"+(o.type==='npc'?'PARLER':o.type==='exit'?'ENTRER':'EXAMINER')+"</em></button>"}).join("");Array.from($("objects").children).forEach(function(el){el.onclick=function(){var o=z.objects.find(function(x){return x.id===el.dataset.id});if(Math.abs(o.x-s.x)<11)interact(o);else target=o}});$("player").style.left=s.x+"%";updateNear();save()}
function updateNear(){var z=zone();near=z.objects.reduce(function(b,o){return Math.abs(o.x-s.x)<Math.abs(((b&&b.x)||999)-s.x)?o:b},null);var close=near&&Math.abs(near.x-s.x)<10;Array.from($("objects").children).forEach(function(e){e.classList.toggle("near",close&&e.dataset.id===near.id)});var verb=near&&(near.type==="npc"?"Parler":near.type==="exit"?"Entrer":"Examiner");$("prompt").innerHTML=close?"<kbd>✦</kbd><span><small>INTERACTION</small>"+verb+" — <b>"+near.name+"</b></span>":"";$("prompt").classList.toggle("on",!!close);$("act").classList.toggle("ready",!!close);$("actHint").textContent=close?verb+" · "+near.name:"Aucun élément";if(!close)near=null}
function reveal(){var e=$("reveal");e.textContent=zone().name;e.classList.remove("on");void e.offsetWidth;e.classList.add("on")}
function travel(o){if(o.need&&!has(o.need))return say("Lautrec","Il me manque une preuve pour continuer.",[{t:"Reprendre l'enquête",a:closeDialogue}]);s.zone=o.to;s.x=o.at;s.objective={street:"Retrouve Mira et la treizième heure.",archives:"Retrouve les quatre signatures.",tunnels:"Découvre qui a ouvert la porte IV.",mirror:"Confronte le Reflet.",bell:"Décide du sort des souvenirs."}[o.to]||s.objective;xp(6);render();reveal()}
function say(name,text,answers){$("speaker").textContent=name.toUpperCase();$("speech").textContent=text;$("portrait").textContent={Mira:"♟",Horloger:"♙",Sorel:"♜","Gardien masqué":"♞","Le Reflet":"♛","La Cloche":"◉",Lautrec:"◆"}[name]||"◇";$("answers").innerHTML="";answers.forEach(function(a,i){var b=document.createElement("button");b.innerHTML="<b>"+(i+1)+"</b><span>"+a.t+"</span>"+(a.need&&!has(a.need)?"<small>Indice requis : "+info[a.need][0]+"</small>":"");b.disabled=a.need&&!has(a.need);b.onclick=a.a;$("answers").appendChild(b)});$("dialogue").classList.add("on");held=0}
function closeDialogue(){$("dialogue").classList.remove("on");save()}
function check(name,bonus,dc,okText,badText){closeDialogue();var die=1+Math.floor(Math.random()*20),total=die+bonus,ok=total>=dc;if(ok)xp(8);$("rollSkill").textContent=name.toUpperCase();$("die").textContent="?";$("rollMath").textContent="Lancer du d20…";$("rollVerdict").textContent="";$("rollStory").textContent="";$("roll").className="roll on";var n=0,t=setInterval(function(){$("die").textContent=1+Math.floor(Math.random()*20);if(++n>12){clearInterval(t);$("die").textContent=die;$("rollMath").textContent=die+" au dé + "+bonus+" compétence = "+total+" · difficulté "+dc;$("rollVerdict").textContent=ok?"RÉUSSITE":"ÉCHEC";$("rollStory").textContent=ok?okText:badText;$("roll").classList.add(ok?"success":"failure")}},55)}
function ending(name,moral,reward){s.flags.ending=name;s.quests[0].done=true;s.objective="Fin obtenue : "+name;s.journal.unshift("FIN — "+name);xp(reward);closeDialogue();toast("Fin : "+name);save()}
var talks={
mira:function(){say("Mira","« Tu es en retard de trois vies. Le quatrième Lautrec efface les traces des précédentes. »",[{t:"Montrer la clé noire",need:"key",a:function(){say("Mira","« Elle ouvre un souvenir. Le billet indique quand : la treizième heure. »",[{t:"Noter la piste",a:function(){addClue("clock","Interroge l'horloger puis visite les Archives.");closeDialogue()}},{t:"Partir",a:closeDialogue}])}},{t:"Observer Mira",a:function(){check("Intuition",7,12,"Elle dit vrai, mais elle a peur.","Son visage reste illisible.")}},{t:"Partir",a:closeDialogue}])},
clockmaker:function(){say("Horloger","« Toutes les horloges mentent depuis que la treizième heure a disparu. »",[{t:"Parler de la treizième heure",need:"clock",a:function(){say("Horloger","« Un homme avec ton visage est descendu sous la ville. Les Archives possèdent son ordre. »",[{t:"Le remercier",a:closeDialogue}])}},{t:"Le questionner",a:function(){check("Charisme",5,11,"Il désigne les Archives.","Il refuse de parler.")}},{t:"Partir",a:closeDialogue}])},
sorel:function(){say("Sorel","« Les registres ne mentent jamais. Les hommes arrachent des pages. »",[{t:"Présenter le billet",need:"note",a:function(){say("Sorel","« Cette encre a cent ans. Cherche le registre au centre. »",[{t:"Enquêter",a:closeDialogue}])}},{t:"Demander le décret",need:"ledger",a:function(){addClue("decree","Descends sous Veyre.");say("Sorel","« Le décret ordonne à Veyre d'oublier chaque vie de Lautrec. »",[{t:"Prendre une copie",a:closeDialogue}])}},{t:"Quitter",a:closeDialogue}])},
masked:function(){say("Gardien masqué","« Sujet IV confirmé. Tu aurais dû tout oublier. »",[{t:"Montrer le décret",need:"decree",a:function(){addClue("origin","Ouvre la porte IV.");say("Gardien masqué","« Le Reflet est le premier Lautrec. C'est toi qui l'as enfermé. »",[{t:"Continuer",a:closeDialogue}])}},{t:"Combattre",a:function(){startBattle("Gardien masqué",28,7,12,35,"origin")}},{t:"Reculer",a:closeDialogue}])},
reflection:function(){say("Le Reflet","« Enfin. Tu as assez changé pour que je ne puisse plus te prévoir. »",[{t:"Tu es le premier Lautrec",need:"origin",a:function(){addClue("truth","Entre dans la salle de la Cloche.");say("Le Reflet","« Je porte tous les souvenirs que tu as refusés. »",[{t:"Accepter",a:closeDialogue}])}},{t:"Lire son regard",a:function(){check("Perception",8,14,"Il craint la clé noire.","Le miroir brouille tout.")}},{t:"Combattre",a:function(){startBattle("Premier Lautrec",42,9,14,70,"truth")}}])},
mechanism:function(){say("La Cloche","« Un nom pour une mémoire. Une mémoire pour une vie. Choisis. »",[{t:"Libérer les souvenirs",need:"truth",a:function(){ending("La ville se souvient",2,100)}},{t:"Effacer le premier Lautrec",need:"origin",a:function(){ending("Le prix d'un nom",-1,110)}},{t:"Contrôler la Cloche",need:"echoes",a:function(){ending("Le maître des silences",-2,125)}},{t:"Attendre",a:closeDialogue}])}
};
function interact(o){o=o||near;if(!o)return;if(o.type==="exit")return travel(o);if(o.type==="npc")return talks[o.id]&&talks[o.id]();if(o.need&&!has(o.need))return say("Lautrec","Cet élément est verrouillé. Il me manque un indice.",[{t:"Continuer",a:closeDialogue}]);var map={note:["note","Trouve la clé noire."],key:["key","Sors et retrouve Mira."],writing:["writing","Interroge les habitants."],ledger:["ledger","Interroge Sorel."],cabinet:["decree","Descends sous Veyre."],tracks:["tracks","Interroge le gardien."],echoes:["echoes","Choisis le destin des souvenirs."]};var a=map[o.id],freshClue=a&&addClue(a[0],a[1]);say("Lautrec",freshClue?"Nouvel indice ajouté au journal.":"J'ai déjà examiné cet élément.",[{t:"Continuer",a:closeDialogue}]);render()}
function startBattle(name,hp,attack,def,reward,next){closeDialogue();s.combat={name:name,hp:hp,maxHp:hp,attack:attack,def:def,reward:reward,next:next,guard:false};renderBattle();$("battle").classList.add("on")}
function renderBattle(){var c=s.combat;if(!c)return;$("enemyName").textContent=c.name;$("enemyHp").textContent=c.hp+"/"+c.maxHp;$("playerHp").textContent=s.hp+"/"+s.maxHp;$("enemyBar").style.width=100*c.hp/c.maxHp+"%";$("playerBar").style.width=100*s.hp/s.maxHp+"%";$("battleButtons").innerHTML="<button data-a='attack'><b>ATTAQUE</b>Dague</button><button data-a='trick'><b>RUSE</b>Intuition</button><button data-a='guard'><b>GARDE</b>Protection</button><button data-a='heal'><b>TONIQUE</b>8 or</button>";Array.from($("battleButtons").children).forEach(function(b){b.onclick=function(){battleTurn(b.dataset.a)}})}
function battleTurn(act){var c=s.combat,text="";if(act==="heal"){if(s.gold<8)return toast("Il faut 8 or");s.gold-=8;s.hp=Math.min(s.maxHp,s.hp+10);text="Lautrec récupère 10 PV."}else if(act==="guard"){c.guard=true;text="Lautrec se protège."}else{var die=1+Math.floor(Math.random()*20),bonus=act==="trick"?6:8;if(die+bonus>=c.def){var dmg=(act==="trick"?5:7)+Math.floor(Math.random()*7);c.hp=Math.max(0,c.hp-dmg);text="Réussite : "+dmg+" dégâts."}else text="L'attaque échoue."}if(c.hp<=0){s.gold+=c.reward;xp(45);if(c.next&&!has(c.next))addClue(c.next,"Poursuis l'enquête.");$("battleLog").textContent="Victoire ! +"+c.reward+" or.";return setTimeout(function(){$("battle").classList.remove("on");s.combat=null;render()},800)}var hit=Math.max(1,c.attack-Math.floor(Math.random()*4)-(c.guard?4:0));c.guard=false;s.hp=Math.max(0,s.hp-hit);text+=" L'ennemi inflige "+hit+" dégâts.";if(s.hp<=0){s.hp=Math.ceil(s.maxHp/2);s.gold=Math.max(0,s.gold-10);$("battle").classList.remove("on");s.combat=null;toast("Lautrec reprend conscience…")} $("battleLog").textContent=text;renderBattle();save()}
function openMenu(type){var titles={hero:"Lautrec",bag:"Inventaire",quests:"Quêtes",journal:"Journal"};$("menuTitle").textContent=titles[type];var h="";if(type==="hero")h="<div class='stats'><div><b>"+s.level+"</b>Niveau</div><div><b>"+s.xp+"</b>XP</div><div><b>"+s.clues.length+"</b>Indices</div></div><div class='row'><i>⚔</i><div><b>Dextérité +8</b><small>Attaque et discrétion</small></div></div><div class='row'><i>✦</i><div><b>Intuition +6</b><small>Enquête et ruse</small></div></div>";if(type==="bag")h=s.inventory.map(function(x){return"<div class='row'><i>⚔</i><div><b>"+x.name+"</b><small>"+x.type+" · puissance "+(x.power||0)+"</small></div></div>"}).join("");if(type==="quests")h=s.quests.map(function(q){return"<div class='row'><i>"+(q.done?"✓":"✦")+"</i><div><b>"+q.name+"</b><small>"+q.text+"</small></div></div>"}).join("");if(type==="journal")h=s.journal.concat(s.clues.map(function(id){return info[id][0]+" — "+info[id][1]})).map(function(x){return"<div class='row'><i>◇</i><div>"+x+"</div></div>"}).join("");$("menuBody").innerHTML=h;$("menu").classList.add("on")}
function loop(t){if(!running)return;var dt=Math.min(.04,(t-last)/1000||0);last=t;if(target&&!$("dialogue").classList.contains("on")){var d=target.x-s.x;if(Math.abs(d)<8){var o=target;target=null;held=0;interact(o)}else held=Math.sign(d)}if(held&&!$("dialogue").classList.contains("on")&&!$("battle").classList.contains("on")){s.x=Math.max(2,Math.min(97,s.x+held*dt*18));$("player").style.left=s.x+"%";$("player").classList.add("walk");$("player").classList.toggle("left",held<0);$("world").style.setProperty("--pan",(s.x-50)*-.08+"%");updateNear()}else $("player").classList.remove("walk");raf=requestAnimationFrame(loop)}
function begin(){$("title").classList.remove("on");$("game").classList.add("on");running=true;last=performance.now();render();reveal();cancelAnimationFrame(raf);raf=requestAnimationFrame(loop)}
$("rollContinue").onclick=function(){$("roll").className="roll";save()};
$("play").onclick=begin;$("restart").onclick=function(){if(confirm("Recommencer la chronologie V9 ?")){s=fresh();save();begin()}};[["left",-1],["right",1]].forEach(function(pair){var b=$(pair[0]);b.onpointerdown=function(e){e.preventDefault();target=null;held=pair[1]};b.onpointerup=b.onpointercancel=b.onpointerleave=function(){held=0}});$("act").onclick=function(){interact()};$("save").onclick=function(){save(true)};$("heroMenu").onclick=function(){openMenu("hero")};document.querySelectorAll("[data-menu]").forEach(function(b){b.onclick=function(){openMenu(b.dataset.menu)}});$("menuClose").onclick=function(){$("menu").classList.remove("on")};$("menu").onclick=function(e){if(e.target.id==="menu")e.currentTarget.classList.remove("on")};addEventListener("pagehide",function(){save()});
})();
